services:
  app:
    image: ghcr.io/abrahamfredrik/flight-controll:latest
    container_name: flask-app
    ports:
      - "3001:3001"
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0

